Update README.md
EvoluServices/api-design-guidelines pull request #1
Opened 2022-08-17 18:18 UTC by higormlima

Atualiza README.md com documentação do API Design Guidelines

2022-08-17 18:57 UTC, plinioumzk reviewed
Seria bom colocar entre crases os paths e URLs.

2022-08-17 18:57 UTC, plinioumzk commented on README.md
> +```
Se colocar `json` depois das crases, o markdown formata certinho em JSON.

2022-08-17 18:57 UTC, plinioumzk commented on README.md
> +<table>
O markdown fornece sintaxe pras tabelas https://www.markdownguide.org/extended-syntax/#tables

2022-08-17 18:57 UTC, plinioumzk commented on README.md
> +Nas APIs da Evoluservices, o path **DEVE** sempre começar como prefixo /apis/, seguidos de
Formatar para `/apis`, entre crases

2022-08-17 19:00 UTC, plinioumzk reviewed
Faltou a parte do índice

2022-08-18 13:13 UTC, higormlima commented on README.md
> +```
done

2022-08-18 13:14 UTC, higormlima commented on README.md
> +<table>
done

2022-08-18 13:14 UTC, higormlima commented on README.md
> +Nas APIs da Evoluservices, o path **DEVE** sempre começar como prefixo /apis/, seguidos de
done

2022-08-18 13:14 UTC, higormlima commented on README.md
> +/v{versão-da-api}/{api-name}. A versão da API **DEVE** seguir as regras conforme descritas na seção
done

2022-08-18 13:14 UTC, higormlima commented
> Faltou a parte do índice



> Seria bom colocar entre crases os paths e URLs.

done

2022-08-18 16:16 UTC, fabio-evo requested changes

2022-08-18 16:16 UTC, fabio-evo commented on README.md
> +  na estratégia `wildcard`(*)
Colocar todos os scopes entre crases: (read, write, *.read, *) e corrigir link

2022-08-18 16:16 UTC, fabio-evo commented on README.md
> +Este Apêndice diz, com mais detalhes, os significados de cada palavra chave descrito
Acho que o apêndice deveria ter A minúsculo.
Faltou o hífen em 'palavra-chave'

2022-08-19 15:58 UTC, higormlima commented on README.md
> +  Ela **DEVE** ser alterada para usar ou UTC (“Z” ou “+00:00”).
done

2022-08-19 15:58 UTC, higormlima commented on README.md
> +* [Definições](#definies)
done

2022-08-19 15:58 UTC, higormlima commented on README.md
> +Sempre que um campo opcional não estiver presente, DEVE-SE preenchê-lo com `null `no JSON representativo. Isso tem efeito positivo em várias das fases ao longo da vida do desenvolvedor consumidor.
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +padrão  [semântico] (https://semver.org/lang/pt-BR/) com adição do
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +versionamento [semântico]([https://semver.org/lang/pt-BR/](https://semver.org/lang/pt-BR/)).
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +Este Apêndice diz, com mais detalhes, os significados de cada palavra chave descrito
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +conforme [RFC2119]([https://www.ietf.org/rfc/rfc2119.txt](https://www.ietf.org/rfc/rfc2119.txt)),
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +1. **PRECISA** ou os termos **OBRIGATÓRIO **ou** MANDATÓRIO**, significa que é um requerimento
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +   determinado mercado exige ou porque um fornecedor sente que a aplicação da regra aprimora o
done

2022-08-19 15:59 UTC, higormlima commented on README.md
> +6. **PODE, É PERMITIDO** ou o adjetivo **OPCIONAL**, significa que a regra é verdadeiramente
done

2022-08-19 17:27 UTC, fabio-evo commented on README.md
> +Este Apêndice diz, com mais detalhes, os significados de cada palavra chave descrito
Opa, o "*A*pêndice" da linha 1053, precisa voltar o A maiúsculo da linha 1051 rsrs

2022-08-19 17:30 UTC, higormlima commented on README.md
> +Este Apêndice diz, com mais detalhes, os significados de cada palavra chave descrito
opa, aqui foi erro meu rsrs

2022-08-19 17:58 UTC, higormlima commented on README.md
> +  na estratégia `wildcard`(*)
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +* **É RECOMENDADO** que no campo `explanation `inclua a descrição padrão para o status code
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +e `action `siga o padrão de formato como especificado a seguir.
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +* **apiVersion**: versão semântica da _implementação _da API. Esta não é a versão da especificação
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +| PATCH | X |  | X | X | X | X | X | X | X |
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +| 200 | Internal Server Error | Significa que houve algum erro interno no servidor. |
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +* 1XX:  é usada apenas para fins informativos. Esta categoria não costuma ser muito utilizada;
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +. Consequentemente, os endpoints **DEVEM** aceitar conteúdos do tipo application/json e também
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +documento [RFC7159]([https://datatracker.ietf.org/doc/html/rfc7159](https://datatracker.ietf.org/doc/html/rfc7159))
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +      no [API Implementation Guidelines](https://docs.google.com/document/d/1oVhpgb9f48dpFqHfzCr65bL7MCB3E-Y3kUekyIlEunI/edit)
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +  operação é [idempotente](link para definição de idempotência) por definição.
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +| POST | 	Cria um recurso ou executa uma operação complexa sobre um recurso. DEVE ser usado para realizar cancelamentos. |
done

2022-08-19 17:58 UTC, higormlima commented on README.md
> +. As quais são representadas, respectivamente, pelos métodos POST, GET, PUT (ou PATCH) e DELETE.
done

2022-08-19 17:59 UTC, higormlima commented on README.md
> +* Você pode consultar mais detalhes no [FAQ] (LInk para o FAQ]. Lá contém os exemplos e outras
ok

2022-08-19 17:59 UTC, higormlima commented on README.md
> +  o [ISO4217]([https://pt.wikipedia.org/wiki/ISO_4217](https://pt.wikipedia.org/wiki/ISO_4217)).
done

2022-08-19 17:59 UTC, higormlima commented on README.md
> +  qual possui uma quantidade similar de caracteres de um UUID.
done

2022-08-19 17:59 UTC, higormlima commented on README.md
> +| Parte | Descrição
done

2022-08-19 18:09 UTC, fabio-evo commented on README.md
> +* [Definições](#definies)
Ainda há alguns links que não funcionaram:

- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#bad-request
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#unauthorized
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#forbidden
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#not-found
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#unprocessable
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#xx-erros-no-servidor
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#scopes-oauth-2.0

Tem mais um caso especial que tem 2 links para o mesmo local, no caso dos tópicos "URL" e "Definições -> URL"
- https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#url

2022-08-19 18:17 UTC, fabio-evo commented on README.md
> +| 200 | Internal Server Error | Significa que houve algum erro interno no servidor. |
faltou um caso na linha do status 401

2022-08-19 18:25 UTC, fabio-evo commented on README.md
> +  na estratégia `wildcard`(*)
Manter parêntesis, exemplo: (read) -> (`read`), se vc remover os parêntesis, os scopes não encaixam mais na frase...

Também, fazer o mesmo com o último asterisco da linha 1049:
De: (*)
Para: (`*`)

2022-08-19 18:30 UTC, fabio-evo requested changes

2022-08-19 18:30 UTC, fabio-evo commented on README.md
> +```
Atualizei os outros comentários.

Também, as keys dos JSONs precisam ficam entre aspas duplas:
```json
{ 
    "transactionNumber": 123681726381,
    "amountValue": 5500,
    "currency": "BRL",
    "..."
}
```

2022-08-22 12:56 UTC, higormlima commented on README.md
> +* [Definições](#definies)
done

2022-08-22 12:56 UTC, higormlima commented on README.md
> +| 200 | Internal Server Error | Significa que houve algum erro interno no servidor. |
done

2022-08-22 12:56 UTC, higormlima commented on README.md
> +  na estratégia `wildcard`(*)
done

2022-08-22 12:56 UTC, higormlima commented on README.md
> +```
done

2022-08-22 19:19 UTC, fabio-evo commented on README.md
> +```
Acho melhor seguir o exemplo que passei, usar aspas na reticências também, assim o GitHub não destaca como um erro.

2022-08-23 10:46 UTC, fabio-evo commented on README.md
> +```
Também acho que vamos ter que representar de outra forma este trecho, pois o JSON não aceita comentários...
![image](https://user-images.githubusercontent.com/100136696/186139276-2706f0a4-fffc-44db-940f-71aab681ef31.png)

2022-08-23 10:49 UTC, fabio-evo commented
No tópico [Método POST](https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#m%C3%A9todo-post), existe um "É RECOMENDADO" sem espaço após a vírgula
![image](https://user-images.githubusercontent.com/100136696/186139686-190db147-09c3-4c07-8bb9-8f667832df22.png)

2022-08-23 12:59 UTC, higormlima commented on README.md
> +      no [API Implementation Guidelines](https://docs.google.com/document/d/1oVhpgb9f48dpFqHfzCr65bL7MCB3E-Y3kUekyIlEunI/edit)
Foi adicionado um comentário para lembrar de recolocar a referência à Api Implementation Guidelines quando estiver pronta. O comentário foi colocado ao final da seção, já que não era entendido ao final do tópico onde ficava a referência  à guideline.

2022-08-23 13:00 UTC, higormlima commented on README.md
> +```
done

2022-08-23 13:01 UTC, higormlima commented
> No tópico [Método POST](https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#m%C3%A9todo-post), existe um "É RECOMENDADO" sem espaço após a vírgula ![image](https://user-images.githubusercontent.com/100136696/186139686-190db147-09c3-4c07-8bb9-8f667832df22.png)

done

2022-08-23 13:01 UTC, higormlima commented
> No tópico [Método POST](https://github.com/EvoluServices/api-design-guidelines/tree/new-readme-api-design-guidelines#m%C3%A9todo-post), existe um "É RECOMENDADO" sem espaço após a vírgula ![image](https://user-images.githubusercontent.com/100136696/186139686-190db147-09c3-4c07-8bb9-8f667832df22.png)

done

2022-08-24 12:19 UTC, merged